AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Service Control Policy (SCP) for Bedrock access restrictions.
  Restricts access to specific foundation models and inference profiles only.

Resources:
  BedrockAccessControlPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      Name: BedrockModelApprovalAndInvocationPolicy
      Description: Manages model approval by blocking unauthorized model invocations while allowing read operations
      Type: SERVICE_CONTROL_POLICY
      Content: |
      #Allow only specific foundation models and inference profiles
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "BlockUnauthorizedModelInvocations",
              "Effect": "Deny",
              "Action": [
                "bedrock:InvokeModel",
                "bedrock:InvokeModelWithResponseStream",
                "bedrock:Converse",
                "bedrock:ConverseStream",
                "bedrock:CreateModelInvocationJob",
                "bedrock:CreateModelCustomizationJob"
              ],
              "NotResource": [
                "arn:aws:bedrock:*::foundation-model/amazon.nova*",
                "arn:aws:bedrock:*::foundation-model/amazon.titan*",
                "arn:aws:bedrock:*::foundation-model/anthropic.claude*",
                "arn:aws:bedrock:*:*:inference-profile/us.amazon.nova*",
                "arn:aws:bedrock:*:*:inference-profile/us.amazon.titan*",
                "arn:aws:bedrock:*:*:inference-profile/us.anthropic.claude*"
              ]
            },
            {
              "Sid": "BlockUnauthorizedModelFamilies",
              "Effect": "Deny",
              "Action": "bedrock:*",
              "Resource": [
                "arn:aws:bedrock:*::foundation-model/meta.*",
                "arn:aws:bedrock:*::foundation-model/mistral.*",
                "arn:aws:bedrock:*::foundation-model/stability.*",
                "arn:aws:bedrock:*::foundation-model/ai21.*",
                "arn:aws:bedrock:*::foundation-model/cohere.*",
                "arn:aws:bedrock:*:*:inference-profile/us.meta.*",
                "arn:aws:bedrock:*:*:inference-profile/us.mistral.*",
                "arn:aws:bedrock:*:*:inference-profile/us.stability.*",
                "arn:aws:bedrock:*:*:inference-profile/us.ai21.*",
                "arn:aws:bedrock:*:*:inference-profile/us.cohere.*"
              ]
            }
          ]
        }

Outputs:
  PolicyId:
    Description: The ID of the created SCP policy
    Value: !Ref BedrockAccessControlPolicy
  PolicyArn:
    Description: The ARN of the created SCP policy
    Value: !GetAtt BedrockAccessControlPolicy.Arn
